#define QWERTY_MIN 0
#define QWERTY 1
#define QWERTY_2 2
#define COLEMAK 3
#define COLEMAK_2 4
#define GAMING 5
#define GAMING2 6
#define GAMING3 7
#define SYMBOL 8
#define MOUSE 9
#define NAV 10
#define FNAV 11
